package me.test.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.test.greendao.note;

import me.test.greendao.noteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;

    private final noteDao noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(noteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        noteDao = new noteDao(noteDaoConfig, this);

        registerDao(note.class, noteDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
    }

    public noteDao getNoteDao() {
        return noteDao;
    }

}
